name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: haydargenc/pre-commit:latest
      steps:
         - name: Log the parent container node version
           run: |
             pre-commit